In [1]:
# Normal import
import numpy as np
from collections import defaultdict
import random
from numpy import random
import matplotlib.pyplot as plt

import networkx as nx
import numpy as np
from dwave.system import LeapHybridSampler
import matplotlib



## Quantum Part
from collections import defaultdict
from dwave.system.samplers import DWaveSampler
from dwave.system.composites import EmbeddingComposite
import dwave.inspector
import dimod
from dwave.system import LeapHybridSampler

#Page Size
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [2]:
A = np.array([[0, 0],
              [0, 0],
              [0, 0],
              [0, 0],
              [-1, -1],
              [-1, 0],
              [-1, 0],
              [0, -1],
              [0, -1],])

G = np.array([[1,0,1,0], 
              [1,0,0,1],
              [0,1,1,0],
              [0,1,0,1],
              [0,0,0,0],
              [1,0,0,0],
              [0,1,0,0],
              [0,0,1,0],
              [0,0,0,1],
             ])
b = np.array([1,1,1,1,-1,0,0,0,0])

c = np.array([-15.0,-10.0])

h = np.array([8,9,5,6])

In [3]:
z = None
if z==None:
    print("None")

None


In [4]:
b = np.array([2,4,1,-3,-1,0,-4,0,0])

In [5]:
lhs = np.sum(b[b<0])
rhs =5
print(lhs)
disturbance = 1e-6

-8


In [6]:
print(rhs - lhs + disturbance)
np.ceil(np.log2(rhs - lhs + disturbance))

13.000001


4.0

In [7]:
lhs = np.array([1,0,1,0,0,0])
r = np.array([0,1,0,0,0,0])
p = np.array([0,1,0,-1,0,0])

In [8]:
np.sum(lhs>0),

(2,)

In [9]:
vector = p==1
print(vector)

[False  True False False False False]


In [10]:
result = np.outer(lhs,lhs)
print(result)
print(np.triu(result,k = 1))

[[1 0 1 0 0 0]
 [0 0 0 0 0 0]
 [1 0 1 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[[0 0 1 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [11]:
np.array_equal(lhs, lhs.astype(bool))  

True

In [13]:
lhs = p
(np.sum(lhs) == 0) and (np.sum(abs(lhs))== 2)

True

In [8]:
s = np.arange(5)
print(s)
print(2**s)

[0 1 2 3 4]
[ 1  2  4  8 16]


In [9]:
ss = 2**s

In [10]:
print(np.outer(ss,s))
print(np.outer(s,ss))

[[ 0  1  2  3  4]
 [ 0  2  4  6  8]
 [ 0  4  8 12 16]
 [ 0  8 16 24 32]
 [ 0 16 32 48 64]]
[[ 0  0  0  0  0]
 [ 1  2  4  8 16]
 [ 2  4  8 16 32]
 [ 3  6 12 24 48]
 [ 4  8 16 32 64]]


In [12]:
a = 0
if not a == 1:
    print("execute")

execute


In [15]:
max(4,-2)

4