In [3]:
%run Make_Questiones.ipynb
import numpy as np
from collections import defaultdict
import random
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")
import time
import csv

In [4]:
N = 3
#M = 5
I = 2
J = 3
K = 5
Channel_upperbound = 20
Data_upperbound = 20
Processing_upperbound = 45
self_looped = 100

In [5]:
Channel_link = Create_channel(N,Channel_upperbound,option = "same",initial_length = 1)
Data_input = Data_Queue(I,J,Data_upperbound)
Data_input_type = Data_Queue_type(I,J,K)
VM_type = VM_Data_type_gen(I,K,N)
VM_speed = VM_Data_processing_speed(Processing_upperbound, VM_type, K)

VM_DP_time = VM_Data_processing_time(Data_input, Data_input_type , VM_speed)
Transmission_time = Channel_Data_transmission_time(Data_input , Channel_link)

In [8]:
print(VM_DP_time)
modified_Transmission_time = Transmission_time[:,1:,:,1:]
modified_Transmission_time[np.isinf(modified_Transmission_time)] = 0  #可不做（只要左，上需要从除去inf，除非不是全连接图）
print(modified_Transmission_time)

[[[ 1.  1. inf]
  [inf inf  4.]
  [inf inf  1.]]

 [[inf inf  1.]
  [ 1. inf inf]
  [inf inf  5.]]]
[[[[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]]


 [[[1. 1. 1.]
   [1. 1. 4.]
   [1. 1. 2.]]

  [[1. 1. 1.]
   [1. 1. 3.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [2. 1. 1.]
   [1. 1. 1.]]]]


In [12]:
# Transmission focusing
Total_time = modified_Transmission_time
for i in range(I):
    for j in range(J):
        for n in range(N):
            Total_time[i,:,j,n] += VM_DP_time[i,j,n]
        

In [22]:
np.sum(np.min(Total_time,(1,3)))

19.0

In [14]:
Total_time[0,:,0,:]

array([[ 2.,  2., inf],
       [ 2.,  2., inf],
       [ 2.,  2., inf]])

In [15]:
Total_time[0,:,1,:]

array([[inf, inf,  5.],
       [inf, inf,  5.],
       [inf, inf,  5.]])

In [16]:
Total_time[0,:,2,:]

array([[inf, inf,  2.],
       [inf, inf,  2.],
       [inf, inf,  2.]])

In [18]:
Total_time[1,:,0,:]

array([[inf, inf,  2.],
       [inf, inf,  2.],
       [inf, inf,  2.]])

In [19]:
Total_time[1,:,1,:]

array([[ 2., inf, inf],
       [ 2., inf, inf],
       [ 3., inf, inf]])

In [20]:
Total_time[1,:,2,:]

array([[inf, inf,  7.],
       [inf, inf,  6.],
       [inf, inf,  6.]])