In [62]:
%run Make_Question_simplified.ipynb
import numpy as np
from collections import defaultdict

import random
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")
import time
import csv

from collections import defaultdict

from dwave.system.samplers import DWaveSampler
from dwave.system.composites import EmbeddingComposite
import networkx as nx
import numpy as np

import dwave.inspector
import dimod


import matplotlib

from matplotlib import pyplot as plt

from dwave.system import LeapHybridSampler

import pandas as pd

import matplotlib.pyplot as plt
import numpy as np
import scipy
import scipy.stats

from tqdm.notebook import tqdm

In [116]:
def Measure(QUBO): 
    width,height = np.shape(QUBO)

    QUBO_dictionary = defaultdict(int)
    for i in range(width):
        for j in range(height):
            QUBO_dictionary[(i,j)] = QUBO[i,j]

    #sampler = EmbeddingComposite(DWaveSampler(solver={'qpu': True}))
    #sampler = EmbeddingComposite(DWaveSampler())
    # Select a solver
    sampler = LeapHybridSampler()

    num_reads = 10000
    #sampleset = sampler.sample_qubo(QUBO, chain_strength = 8, num_reads=num_reads)
    #sampleset = sampler.sample_qubo(QUBO, num_reads=num_reads)
    sampleset = sampler.sample_qubo(QUBO)


    #sample = sampleset.first.sample
    #energy = sampleset.first.energy
    #print(sample,energy)
    OP = sampleset.to_pandas_dataframe()
    

    OP = OP.sort_values("energy")
    OP_final = OP.to_numpy()

    rank = 0


    OP_opt = OP_final[rank,:].flatten()
    sample = OP_opt.astype(int)
    
    return sample, sampleset



In [121]:
N = 3
#M = 5
I = 3
J = 3
K = 4
Data_upperbound = 20
Processing_upperbound = 20
Data_input = Data_Queue(I,J,Data_upperbound)

Data_input_type = Data_Queue_type(I,J,K)
VM_type = VM_Data_type_gen(I,K,N)

VM_speed = VM_Data_processing_speed(Processing_upperbound, VM_type, K)
VM_DP_time = VM_Data_processing_time(Data_input, Data_input_type , VM_speed)

modified_VM_DP_time =np.copy(VM_DP_time)
modified_VM_DP_time[np.isinf(modified_VM_DP_time)]=np.inf

T_max_true = little_greedy_algorithm(VM_DP_time,I,J,N)
print(VM_type)
print(Data_input_type)
print(VM_DP_time)
#print(np.min(VM_DP_time.reshape(I*J,N),1))
T_max= T_max_true + 1
#T_max += 1
print("T_max is ",T_max_true)
#print("let t = 1 unit of time")

[[2 3 4]
 [1 3 4]
 [1 2 4]]
[[4 2 1]
 [3 4 2]
 [1 2 4]]
[[[ 1.  1. 10.]
  [ 6. inf  1.]
  [inf  1.  1.]]

 [[ 1.  1. inf]
  [ 2.  1. 13.]
  [ 1. inf  1.]]

 [[inf  1.  1.]
  [ 5. inf  1.]
  [ 2.  1. 17.]]]
T_max is  10


In [135]:
position_dictionary, Total = Make_dictionary(I,J,N,T_max)
QUBO_init = np.zeros((Total, Total))
P = {
    "Obj": 1,
    "C1":  600,
    "C2":  600,
    "C3":  600,
    "C4":  600,
    "C5":  1200,
    "C6":  600,
    "C7":  2000,
    "C8":  1200,
    "C9":  600,
    "Cadd":  600,
    "Cadd1":  600,
    "Cadd2":  600,
    "Caddz":  600,
}
QUBO_0 = mk_QUBO_0(I,J,N,T_max,QUBO_init,P)
QUBO_1 = mk_QUBO_1(I,J,N,T_max,QUBO_init,VM_type,Data_input_type,position_dictionary,P)
QUBO_2 = mk_QUBO_2(I,J,N,T_max,QUBO_init,VM_type,Data_input_type,position_dictionary,P)
QUBO_3 = mk_QUBO_3(I,J,N,T_max,QUBO_init,VM_type,Data_input_type,position_dictionary,P)
QUBO_4 = mk_QUBO_4(I,J,N,T_max,QUBO_init,VM_type,Data_input_type,position_dictionary,P)
QUBO_5 = mk_QUBO_5(I,J,N,T_max,QUBO_init,VM_type,Data_input_type,position_dictionary,modified_VM_DP_time,P)
QUBO_6 = mk_QUBO_6(I,J,N,T_max,QUBO_init,VM_type,Data_input_type,position_dictionary,modified_VM_DP_time,P)
QUBO_7 = mk_QUBO_7(I,J,N,T_max,QUBO_init,VM_type,Data_input_type,position_dictionary,modified_VM_DP_time,P)
#QUBO_8 = mk_QUBO_8(I,J,N,T_max,QUBO_init,VM_type,Data_input_type,position_dictionary,modified_VM_DP_time,P)
QUBO_add = mk_QUBO_add(I,J,N,T_max,QUBO_init,VM_type,Data_input_type,position_dictionary,modified_VM_DP_time,P)

QUBO_add_1 = mk_QUBO_add_1(I,J,N,T_max,QUBO_init,VM_type,Data_input_type,position_dictionary,modified_VM_DP_time,P)
QUBO_add_2 = mk_QUBO_add_2(I,J,N,T_max,QUBO_init,VM_type,Data_input_type,position_dictionary,modified_VM_DP_time,P)

QUBO_add_z = mk_QUBO_add_z(I,J,N,T_max,QUBO_init,VM_type,Data_input_type,position_dictionary,modified_VM_DP_time,P)

QUBO = np.zeros_like(QUBO_init)
QUBO = QUBO_0 * P['Obj'] + QUBO_add + QUBO_1 + QUBO_2 + QUBO_3 + QUBO_4 + QUBO_5 + QUBO_6 + QUBO_7 + QUBO_add_z + QUBO_add_1 + QUBO_add_2# + QUBO_8
#show_graph(QUBO) 
#print(len(position_dictionary))
QUBO,position_dictionary = mk_QUBO_8_alt(I,J,N,T_max,QUBO,VM_type,Data_input_type,position_dictionary,modified_VM_DP_time,P)
#print(len(position_dictionary),np.shape(QUBO))
QUBO,position_dictionary = mk_QUBO_9_alt(I,J,N,T_max,QUBO,VM_type,Data_input_type,position_dictionary,modified_VM_DP_time,P)
#print(len(position_dictionary),np.shape(QUBO))


z_0100
z_0120
z_0210
z_0220
z_1100
z_1110
z_1120
z_1200
z_1220
z_2100
z_2120
z_2200
z_2210
z_2220


In [147]:
num_runs = 90
Success = np.zeros(num_runs)
qpu_access_time = []
qpu_charge_time = []
run_time = []
QUBO_time = []
Obj_time = []


for num in tqdm(range(num_runs)):
    sample,sampleset = Measure(QUBO)
    #dir(sa mpleset)
    Constraint = np.zeros(12)
    Constraint[0] = check_C1 (position_dictionary,sample,I,J,VM_type,Data_input_type)
    Constraint[1] = check_C2 (position_dictionary,sample,I,J,N,T_max)
    Constraint[2] = check_C3 (position_dictionary,sample,I,J,N,T_max)
    Constraint[3] = check_C4 (position_dictionary,sample,I,J,N,T_max)
    Constraint[4] = check_C5 (position_dictionary,sample,I,J,VM_type,Data_input_type,T_max,modified_VM_DP_time)
    Constraint[5] = check_C6 (position_dictionary,sample,I,J,N,T_max)
    Constraint[6] = check_C7 (position_dictionary,sample,I,J,N,T_max)
    Constraint[7] = check_C8_alt(position_dictionary,sample,I,J,VM_type,Data_input_type,T_max,modified_VM_DP_time)
    Constraint[8] = check_C9 (position_dictionary,sample,I,J,VM_type,Data_input_type,T_max,modified_VM_DP_time)
    Constraint[9] = check_C_add(position_dictionary,sample,I,J,N,VM_type,Data_input_type,T_max)
    Constraint[10] = check_C_add_1(position_dictionary,sample,I,J,N,T_max)
    Constraint[11] = check_C_add_2(position_dictionary,sample,I,J,N,T_max)
    
    
    
    print("Constraint_1: ",check_C1 (position_dictionary,sample,I,J,VM_type,Data_input_type))
    print("Constraint_2: ",check_C2 (position_dictionary,sample,I,J,N,T_max))
    print("Constraint_3: ",check_C3 (position_dictionary,sample,I,J,N,T_max))
    print("Constraint_4: ",check_C4 (position_dictionary,sample,I,J,N,T_max))
    print("Constraint_5: ",check_C5 (position_dictionary,sample,I,J,VM_type,Data_input_type,T_max,modified_VM_DP_time))
    print("Constraint_6: ",check_C6 (position_dictionary,sample,I,J,N,T_max))
    print("Constraint_7: ",check_C7 (position_dictionary,sample,I,J,N,T_max))
    print("Constraint_8: ",check_C8_alt(position_dictionary,sample,I,J,VM_type,Data_input_type,T_max,modified_VM_DP_time))
    print("Constraint_9: ",check_C9 (position_dictionary,sample,I,J,VM_type,Data_input_type,T_max,modified_VM_DP_time))
    print("Constraint_add: ",check_C_add(position_dictionary,sample,I,J,N,VM_type,Data_input_type,T_max))
    print("Constraint_add_p: ",check_C_add_1(position_dictionary,sample,I,J,N,T_max))
    print("Constraint_add_z: ",check_C_add_2(position_dictionary,sample,I,J,N,T_max))
    
    Success[num] = int(Constraint.all()) 
    
    qpu_access_time.append(sampleset.info['qpu_access_time']/(10**6))
    qpu_charge_time.append(sampleset.info['charge_time']/(10**6))
    run_time.append(sampleset.info['run_time']/(10**6))
    
    p_ = np.zeros((I,J,N,T_max))
    opt_time = 0
    for i in range(I):    
        for j in range(J):  
            for m in range(N):
                for t in range(T_max):
                    p_[i,j,m,t] = sample[position_dictionary['p_%d%d%d%d'%(i,j,m,t)]]
                    if j == J-1:
                        opt_time += t * sample[position_dictionary['p_%d%d%d%d'%(i,j,m,t)]]
    
    _,_,_,time_final = np.where(p_)
    
    QUBO_time.append(np.max(time_final))
    Obj_time.append(opt_time)            
    
    

Constraint_1:  True
Constraint_2:  True
Constraint_3:  True
Constraint_4:  True
Constraint_5:  True
Constraint_6:  True
Constraint_7:  False
Constraint_8:  True
Constraint_9:  True
Constraint_add:  True
Constraint_add_p:  True
Constraint_add_z:  True
Constraint_1:  True
Constraint_2:  True
Constraint_3:  True
Constraint_4:  True
Constraint_5:  True
Constraint_6:  True
Constraint_7:  False
Constraint_8:  False
Constraint_9:  True
Constraint_add:  True
Constraint_add_p:  False
Constraint_add_z:  True
Constraint_1:  True
Constraint_2:  True
Constraint_3:  True
Constraint_4:  True
Constraint_5:  True
Constraint_6:  True
Constraint_7:  False
Constraint_8:  True
Constraint_9:  True
Constraint_add:  True
Constraint_add_p:  False
Constraint_add_z:  True
Constraint_1:  True
Constraint_2:  True
Constraint_3:  False
Constraint_4:  True
Constraint_5:  False
Constraint_6:  True
Constraint_7:  True
Constraint_8:  True
Constraint_9:  True
Constraint_add:  True
Constraint_add_p:  False
Constraint_add_

Constraint_1:  True
Constraint_2:  True
Constraint_3:  True
Constraint_4:  True
Constraint_5:  True
Constraint_6:  True
Constraint_7:  True
Constraint_8:  True
Constraint_9:  True
Constraint_add:  True
Constraint_add_p:  False
Constraint_add_z:  False
Constraint_1:  True
Constraint_2:  True
Constraint_3:  True
Constraint_4:  True
Constraint_5:  True
Constraint_6:  True
Constraint_7:  True
Constraint_8:  False
Constraint_9:  True
Constraint_add:  True
Constraint_add_p:  True
Constraint_add_z:  True
Constraint_1:  True
Constraint_2:  True
Constraint_3:  True
Constraint_4:  True
Constraint_5:  False
Constraint_6:  True
Constraint_7:  True
Constraint_8:  True
Constraint_9:  True
Constraint_add:  True
Constraint_add_p:  True
Constraint_add_z:  True
Constraint_1:  True
Constraint_2:  True
Constraint_3:  True
Constraint_4:  True
Constraint_5:  False
Constraint_6:  True
Constraint_7:  True
Constraint_8:  False
Constraint_9:  True
Constraint_add:  True
Constraint_add_p:  True
Constraint_add_z: 

Constraint_1:  True
Constraint_2:  True
Constraint_3:  True
Constraint_4:  True
Constraint_5:  True
Constraint_6:  True
Constraint_7:  True
Constraint_8:  False
Constraint_9:  True
Constraint_add:  True
Constraint_add_p:  False
Constraint_add_z:  False
Constraint_1:  True
Constraint_2:  True
Constraint_3:  True
Constraint_4:  True
Constraint_5:  True
Constraint_6:  True
Constraint_7:  False
Constraint_8:  True
Constraint_9:  True
Constraint_add:  True
Constraint_add_p:  True
Constraint_add_z:  True
Constraint_1:  True
Constraint_2:  True
Constraint_3:  True
Constraint_4:  True
Constraint_5:  True
Constraint_6:  True
Constraint_7:  False
Constraint_8:  True
Constraint_9:  True
Constraint_add:  True
Constraint_add_p:  True
Constraint_add_z:  False
Constraint_1:  True
Constraint_2:  True
Constraint_3:  True
Constraint_4:  True
Constraint_5:  False
Constraint_6:  True
Constraint_7:  False
Constraint_8:  True
Constraint_9:  True
Constraint_add:  True
Constraint_add_p:  True
Constraint_add_z

SolverFailureError: Problem not accepted because user stzjd15@gmail.com has insufficient remaining solver access time in project DEV

In [148]:
int(True)

1

In [149]:
Constraint.all()

False

In [150]:
Success

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.])

In [151]:
Constraint.all()

False

In [153]:
print(qpu_access_time)
print(qpu_charge_time) 
print(run_time) 
print(QUBO_time) 
print(Obj_time) 
print(T_max_true) 

[0.06592, 0.065012, 0.065909, 0.065014, 0.065013, 0.065014, 0.065931, 0.065908, 0.065928, 0.065903, 0.065025, 0.065023, 0.032515, 0.0, 0.03296, 0.032945, 0.032512, 0.065914, 0.065917, 0.065014, 0.065895, 0.065015, 0.065022, 0.065913, 0.065018, 0.065013, 0.065012, 0.065012, 0.065018, 0.065901, 0.065905, 0.065024, 0.065018, 0.065911, 0.065015, 0.065908, 0.065915, 0.065897, 0.065916, 0.065914, 0.065925, 0.065012, 0.065909, 0.065011, 0.065009, 0.032499, 0.065911, 0.065907, 0.065904, 0.065912, 0.065916, 0.065912, 0.065019, 0.065915, 0.065918, 0.065014, 0.065916, 0.065003, 0.032503, 0.065915, 0.065913, 0.065039, 0.065029, 0.065018, 0.065915, 0.065026, 0.065915, 0.065026, 0.065924, 0.065034, 0.065921, 0.065034, 0.065926, 0.065024, 0.065913, 0.065915, 0.06591, 0.065927, 0.065026, 0.065015, 0.065027, 0.065025, 0.065015, 0.065027, 0.065037, 0.065018, 0.065029, 0.065018]
[3.628556, 3.623086, 3.634574, 3.626256, 3.626876, 3.634214, 3.629526, 3.635742, 3.631347, 3.627401, 3.633794, 3.62959, 3.62431

In [115]:
QUBO_shape = np.shape(QUBO)
np.save('I3J3N3/qpu_access_time',qpu_access_time)
np.save('I3J3N3/qpu_charge_time',qpu_charge_time)
np.save('I3J3N3/run_time',run_time)
np.save('I3J3N3/QUBO_time',QUBO_time)
np.save('I3J3N3/Obj_time',Obj_time)
np.save('I3J3N3/Success',Success)
np.save('I3J3N3/QUBO_shape',QUBO_shape)
np.save('I3J3N3/T_max_true',T_max_true)